### ISSUE TITLE
Internal server Error after switch to enterprise theme!

### ISSUE THREAD

**Issue by vpadhariya** [humhub/humhub-modules-enterprise-theme#29]
Hello, 

I just switched to this theme on my live environment setup and I got this error.

I am having latest HH installed 

**HumHub  Professional Edition - SaaS
Version: 1.17.3-master**

`
Warning  Fri, 23 May 2025 13:27:38 +0200 [enterprise-theme]
Configuration at /srv/www/htdocs/sw7co/modules/enterprise-theme has an invalid event configuration: class 'humhub\modules\enterpriseTheme\Events' does not exist.
`

`Error  Fri, 23 May 2025 13:27:38 +0200 [ui]
Could not load module to fetch themes! Module: enterprise-theme Error: Failed to instantiate component or class "humhub\modules\enterpriseTheme\Module".`

**Comment by luke-** [comment]
Just flushed the caches. Can you please try again?

**Comment by vpadhariya** [comment]
hey @luke- thanks for prompt reply.

In live when I switch to enterprise, I instatnly got 500 error, nothing works so I can't do it!

also this instance is in HH cloud, and I only have FTP access.

![Image](https://github.com/user-attachments/assets/58a1cdf8-d04a-45b1-b5fe-131b02978628)

**Comment by luke-** [comment]
@vpadhariya Is it possible to update your instance to the latest `master`? Maybe it's related to an cache issue which is fixed in the lastest saas update.

**Comment by vpadhariya** [comment]
@luke- there is no luck. I still get the same error.

We have Redis cache setup on Humhub Live instance and I have no option to flush cache. is there other way around?

**Comment by luke-** [comment]
There is also a ticket in our support system. Please continue to use this channel.

**Comment by vpadhariya** [comment]
@luke- can you tell me which channel please? provide url please

**Comment by luke-** [comment]
@vpadhariya hello@humhub.com - Keith is already in contact with us.
